### ISSUE TITLE
Why don't I have File Manager in the left menu

### ISSUE THREAD

**Issue by xafdl123github** [orchest/orchest#1050]
I can not find File Manager menu in the left menu，But it's on the official website，Can anyone help me?

**Comment by astrojuanlu** [comment]
Hello @xafdl123github, thanks for your interest in Orchest!

At the moment the Orchest Cloud instances are still using an older version, namely v2022.03.6, because we haven't completed the migration to Kubernetes for those yet. As a result, Cloud users like you are not yet enjoying some of the latest features we have been pushing to the open-source version.

My recommendation is:

- If you want to try out the latest and greatest Orchest features, you can [install it locally](https://docs.orchest.io/en/stable/getting_started/installation.html) (should be more or less straightforward on Linux and WSL2)
- If you want to have them in your Orchest Cloud instance, give us a few extra days so we can complete the migration.

I'm keeping this issue open until the migration happens so it's more visible.

**Comment by xafdl123github** [comment]
Hello @astrojuanlu Thank you very much.  As you say. I deployed orchest via orchest-cli on a minikube cluster.  The orchest version is v2022.06.5.  The reason why there is no File Manger menu on the left is the version not the latest?

**Comment by astrojuanlu** [comment]
Hi @xafdl123github , if you deployed v2022.06.5 with minikube you should have it. Could you please share a screenshot of what you see?

**Comment by xafdl123github** [comment]
Thank you again @astrojuanlu. 
![1](https://user-images.githubusercontent.com/44426610/175221173-1da630e5-d71f-4b39-a73b-19078922b724.png)

**Comment by astrojuanlu** [comment]
@xafdl123github you should see the File Manager if you browse to Pipelines:


https://user-images.githubusercontent.com/316517/175222498-8d5af670-3fe3-4f70-887c-3ecc2a3d9e94.mp4

**Comment by xafdl123github** [comment]
@astrojuanlu Thanks, I see

**Comment by ricklamers** [comment]
@xafdl123github thanks for bringing this up. We'll be sure to update our screenshots once Orchest Cloud has migrated (which we expect to happen in the next few weeks).
