### ISSUE TITLE
I add a redis service in the pipeline. But I can not find the service in the 'Running services' section in the pipeline

### ISSUE THREAD

**Issue by xafdl123github** [orchest/orchest#1070]
I am sure the state of redis service is running. But I can not find the service in the 'Running services' section in the pipeline

![image](https://user-images.githubusercontent.com/44426610/176127078-a7e0150d-9344-4564-8183-ab26ee29572c.png)

![image](https://user-images.githubusercontent.com/44426610/176126755-9e1767b8-0c99-4455-8969-5d8ffb22a03f.png)

**Comment by ricklamers** [comment]
Hi @xafdl123github thanks for letting us know. Services that are not exposed are currently not listed in that dropdown. The message in the dialog is confusing (the `redis` service *is* probably running for you) and we will update it to properly show when services are running, but have no endpoints (ports) exposed.

Since we've moved to `k8s` exposing is required for network communication with the service, so we'll update the template configuration of the `redis` service to have the `redis` port exposed by default (note, it will still require authentication by default too, so it's not publicly accessible).

**Comment by ricklamers** [comment]
The easy fix for you, is to expose the Redis service:

![image](https://user-images.githubusercontent.com/1309307/176134055-90f0e5f8-ac53-4b05-b022-2cc4a1adee76.png)

**Comment by ricklamers** [comment]
For reference, I've changed the default template config for the `redis` service https://github.com/orchest/orchest/commit/85416c2f14fdf2ef32db0c43c1ddfe7fe049a9e9
