### ISSUE TITLE
After setting up MLFlow server (in `Services`) the session won't start 

### ISSUE THREAD

**Issue by cavriends** [orchest/orchest#1098]
**Describe the bug**
After setting up MLFlow server (according to [scenario 3](https://www.mlflow.org/docs/latest/tracking.html)) as a service in `SERVICES` and restarting the session, the session fails to start. The status stays on `SESSION STARTING`. 

**Expected behavior**
I expect the session to restart with the MLFlow UI available on the specified port (default is `5000`)

**To Reproduce**

Create the image according to the set-up script shown below and setup a service according to the configuration below. After that's done restart the session.

```
Image
Python 3 (i.e. orchest/base-kernel-py I presume)
Set-up script: mamba install -y kaggle mlflow unzip

Services
Name: mlflow
Environment: Python 3
Command: mlflow server
Args: --backend-store-uri file://run/project-dir/mlflow/mlruns/
Mounts: /project-dir
Ports: 5000
```

**Screenshots**
<img width="598" alt="image" src="https://user-images.githubusercontent.com/4497501/178153599-3fd87cdd-d4a0-45c2-8992-dcac0b9fb0d3.png">

**Environment**
The error occcured in `Orchest Cloud`

- OS (e.g. macOS): macOS Monterey 12.4 (MacBook Pro (16-inch, 2019))
- Browser (e.g. Chrome): Firefox 102.0.1 (64-bit)
- Orchest's version (in the settings page): v2022.07.1

**Comment by astrojuanlu** [comment]
Hi @cavriends, sorry you're experiencing problems and thanks for opening this issue. While we try to reproduce this on our end, could you check if you spot anything suspicious in the logs? The `Logs` button should take you to a view where you can see the service logs as well.

**Comment by astrojuanlu** [comment]
Also, what image are you using for the service?

**Comment by cavriends** [comment]
Hi @astrojuanlu , thanks for picking it up this quickly! The logs are empty and I have used the image from the environment (clicked on `image` and selected an `environment` (default `Python 3`) in the pop-up).

**Comment by astrojuanlu** [comment]
Thanks @cavriends, I confirm that the session gets stuck at "Starting..." and that the logs are empty for me as well.

**Comment by yannickperrenet** [comment]
I guess the issue comes from the fact that the MLflow docs mention running  `mlflow server <args>` ([source](https://mlflow.org/docs/latest/tracking.html#scenario-3-mlflow-on-localhost-with-tracking-server)) whereas the `Args (optional)` in the Services template in Orchest should actually be all the arguments passed to the executable.

So to fix your issue you need to set:
* `Command (optional)` -> `mlflow`
* `Args (optional)` -> `server --backend-store-uri file://run/project-dir/mlflow/mlruns/`

@cavriends I tested my proposed change on `v2022.07.2`. Should work on `v2022.07.1` as well.

@astrojuanlu I would say this is another point where the usage of Services is unclear.

**Comment by cavriends** [comment]
Thanks @yannickperrenet! Luckily this is quite an easy fix.
