### ISSUE TITLE
Documentation: Comparisson to Kedro

### ISSUE THREAD

**Issue by Make42** [orchest/orchest#1103]
[Kedro](https://kedro.readthedocs.io/) is somewhat similar to orchest. A key difference that I see is that kedro does not support interaction within the graphs that are displayed by https://github.com/kedro-org/kedro-viz. Besides that, kedro seems to be more powerful on nearly every other front. (That might also be a disadvantage if one wants something light-weight.) Can you provide information on how Orchest is advantageous or disadvantageous in general and regarding features?

**Comment by ricklamers** [comment]
We're working on a detailed comparison page to alternatives (e.g. Airflow, Azure Data Factory, Kedro, etc.).

Let me start by saying we think Kedro is an awesome project. However, there are quite a few differences between Orchest and Kedro. Most are likely the result of different design choices (probably stemming from different design goals). Skim the list to find out which tool is the best fit for _your personal requirements_.

Here's a list of some of the important differences that come to mind:
- Kedro is Python specific, while Orchest is container workload centric and language agnostic. Orchest ships integrated language support for Python, R, Julia, JavaScript and Bash invocations (e.g. easily invoke `dbt` or `meltano` CLI tools in your pipeline data workflows).
- Orchest handles container image building for you. This means you can handle code dependencies that go beyond `pip` (limit of Kedro). Check out [Orchest environments](https://docs.orchest.io/en/stable/fundamentals/environments.html) for more details.
- Kedro is more opinionated (data engineering convention, where should you put what, see their [docs](https://kedro.readthedocs.io/en/stable/faq/faq.html#what-is-data-engineering-convention)), Orchest lets you decide project file structure completely.
- Kedro is highly configurable/flexible. This is can be an advantage if you need the flexibility but can also be a disadvantage because of the complexity those different configuration options introduce.
- Jupyter Notebooks don't need to be converted to be used inside Orchest pipelines as steps (Kedro calls steps nodes).
- Orchest maintains all previous pipeline runs and logs and lets you search through them (including the version of code they ran with and artifacts that were produced, e.g. rendered notebooks that were steps in the pipeline you ran). Check out the [Jobs](https://docs.orchest.io/en/stable/fundamentals/jobs.html) feature.
- Orchest manages a bundled Argo for you so you don't have to. Using Kedro on Kubernetes means deploying/managing/configuring Kubeflow or Argo yourself.
- Orchest ships a workbench inside the browser (including a pre-configured JupyterLab). That means you can deploy Orchest on a server and provide your team access, they can then directly edit code, run pipelines interactively, and deploy jobs in production configuration _all directly from their browser_.
- As you mentioned, Orchest has a graphical pipeline editor to update your pipeline definition (the pipeline itself will be saved and versioned as a simple JSON file in your project repository).

We'll make available a more exhaustive comparison once that page goes live.

Thanks for asking this question! I'm sure some other people have the exact same one.

**Comment by Make42** [comment]
Very nice, thank you! Make sure to include ClearML (if you want to) in your comparisons, as it also has DAG execution aka workflows aka pipelines.

**Comment by ricklamers** [comment]
@Make42 good idea! We'll add it to our shortlist of candidates for comparison.

**Comment by Make42** [comment]
@ricklamers Now that I am on a roll... MLRun might also a candidate.
