### ISSUE TITLE
UI element to show that data is stored in the memory-server

### ISSUE THREAD

**Issue by yannickperrenet** [orchest/orchest#132]
When working interactively you might want to see for which step the data is actively stored in the memory-server. Although on the other hand you also don't see what state is still active after running cells in a Jupyter Notebook.

In addition, the fact that it shows “completed” as a status of a step can already give enough of an indication whether or not the data is in the store.

@ricklamers @fruttasecca Thoughts?

**Comment by ricklamers** [comment]
It could be a nice to have in the future, because I’ve not noticed it as confusing or missing during my projects in Orchest. You can quickly call get_inputs() to check if they are available.

in addition, since you can also have data passed through both disk and memory (and perhaps more in the future) that would also need to be communicated along with it. In addition to _when_ it was outputted.

I’d like to park this as a neat idea but not necessary at the moment.

**Comment by yannickperrenet** [comment]
We no longer ship the `memory-server`, and so I have translated the issue to disk data passing and created an issue for it (#1022).
