### ISSUE TITLE
Unified approach for alternative Jupyter kernels like jupyter-xeus

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#138]
Currently the Jupyter Enterprise Gateway (JEG) requires a container image that includes the kernel launcher and language dependencies for each remote kernel.

This implies that we require at least 1 container image per kernel currently. The JEG project has provided [kernel-py](https://github.com/jupyter/enterprise_gateway/tree/master/etc/docker/kernel-py)/[kernel-r](https://github.com/jupyter/enterprise_gateway/tree/master/etc/docker/kernel-r), and we created our own kernel-py with GPU support and kernel-julia to support GPU-enabled Python/Julia kernels in Orchest.

Because of the proliferation of kernels through projects such as [jupyter-xeus](https://github.com/jupyter-xeus/xeus) we want to create a more generic image creation process that we can re-use for all types of kernels. This could be as simple as a well structured Dockerfile and build script.

Nothing is set in stone regarding an implementation approach, and we should seek collaboration on this with the Jupyter Enterprise Gateway project to reduce duplicate effort and maximize community benefit.

**Comment by yannickperrenet** [comment]
@ricklamers With the introduction of the javascript kernel (-> https://github.com/orchest/build-kernel-javascript) and the approach taken there, I feel like we can close this issue.

I don't see us going for an alternative approach in the near future and sticking with the current kernels that we support (as the majority of users are happy with our current kernels).

Since I am leaning more towards closing, instead of keeping an issue open for a very long, I am closing the issue. Feel free to re-open if you disagree.
