### ISSUE TITLE
List project environment variables in the pipeline settings environment variable editor

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#142]
Currently, you can't see the project level environment variables that have been defined in the pipeline settings environment variable view. In user interviews this came across as confusing.

We should list the project level environment variables and allow them to be overridden similar to how they are listed in the job edit/create view.

Since users can also add new environment variables in the pipeline settings view we should indicate when a user is overriding the project level environment variable using some type of visual indicator.

**Comment by yannickperrenet** [comment]
> We should list the project level environment variables and allow them to be overridden similar to how they are listed in the job edit/create view.

I don't think it makes sense to allow them getting overridden. For jobs the impact is different, since the override is for the job only. However, when overriding the project level environment variables in a pipeline you are overriding them for all pipelines (in that project). 

So if the override would be pipeline only, then it makes a lot of sense to me.

**Comment by yannickperrenet** [comment]
Implemented in 2d658e3fe98487e24074fb135099ff220a1f38b5
