### ISSUE TITLE
How to deploy this on OpenShift or kubernetes?

### ISSUE THREAD

**Issue by arm2arm** [orchest/orchest#195]
Hello everybody,
we are impressed by the nice project.
Are there way to deploy it on the kubernetes or openshift cluster?
What I am trying now just run the container inside the OpenShift, but without environmental variables the container failing:
 error: couldn't get deployment orchest-ctl-1: Get https://172.30.0.1:443/api/v1/namespaces/orcrest/replicationcontrollers/orchest-ctl-1:  dial tcp 172.30.0.1:443: connect: no route to host

Should I somehow provide a KUBERNETES_SERVICE_HOST??

**Comment by ricklamers** [comment]
Hi @arm2arm! Thanks for raising this issue.

We don't support k8s at the moment (see https://github.com/orchest/orchest/issues/82). The reason why it's not easy to run Orchest on OpenShift/k8s is because we make pretty extensive use of the Docker SDK to enable some of the core features of Orchest.

Mainly dynamic image building for environments and our custom scheduler that allows for partial execution of pipeline DAGs and integration of JupyterLab container based kernels.

In the future we'll invest time in supporting more diverse deployment configurations. But as a small team we are limited in the number of configurations we can support.
