### ISSUE TITLE
pipeline.orchest pipeline file not found when quickly viewing a pipeline run

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#208]
This could potentially be caused by the file not yet being copied from the snapshot of the project.

We should handle this edge case more cleanly. Currently we block viewing a job in the JobView if the status of the run is PENDING. But apparently the status STARTED doesn’t guarantee that the orchest.pipeline file has been copied.

**Comment by ricklamers** [comment]
Note: hard to reproduce. Tracking whether this pops up again for now.

**Comment by yannickperrenet** [comment]
Not sure whether I understood correctly, but I went through the following steps to try and reproduce the bug (without success).

(Trying to do this as quickly as possible.)
1. Create a job
2. Run the job
3. Inspect the job and view the pipeline

Since the issue has not popped up again, I couldn't reproduce it and I was unsure whether I went through the right reproduction steps. I will close this issue for now.

Note: Other considerations include; large project directory that has to be copied for the snapshot, a lot of other IO happening on disk whilst creating the job.
