### ISSUE TITLE
Clean up old Orchest images after update

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#213]
Currently the updater does not remove the old images (neither command line, nor web updater). 

We should keep in mind that we would prefer to support letting Orchest run during updating. So ideally it would remove dangling images only on e.g. start such that it can clean images that are not in use anymore.

**Comment by yannickperrenet** [comment]
The `update` is split from `restart` because a `restart` would clean up images and thereby also shutting down the Orchest application before starting it. When invoking an `update` it is up to the user whether they also want to `restart`, to help the user decide we actually advice them (through an echo to the terminal) to `restart` for the changes to take effect.

The web updater actually runs a restart for the user and so old images are cleaned up.

What is happening in the `update` however is that environment images are cleaned up as otherwise an old version of the SDK could be used when running Orchest. So it might be the case that, if a pipeline is running (and thus uses environment images) that then the environment images cannot be cleaned/removed and thus resulting in an error (which then results in the `restart` command in the web updater to never be triggered, although unlikely due to the extensive try-except block structure).

So this issue is somewhat connected to #197.

I will look into it the moment my internet improves as currently running the updater would take too long.

**Comment by ricklamers** [comment]
I don’t think Docker cleans up the old images (those running during update) that are now no longer tagged because the update replaced it during pull. Or am I missing something?
