### ISSUE TITLE
Warning about multiple invocations to orchest.output overriding old outputs

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#219]
Even though this behavior is in the contract of the `orchest.output(...)` behavior, it would be good to warn users when they invoke output multiple times that the old output is overridden. As the use case for legitimately calling `orchest.output(...)` multiple times in a single step, knowing it overrides the previous output, is quite esoteric and probably not what the user intended.

In the future we might reconsider the `orchest.output(...)` override behavior, instead allowing some sort of accumulation of outputs during the execution of a script.

**Comment by ricklamers** [comment]
Note: would be nice to have 'rich output' in the Notebook for the warnings using something like `logger.warning` (make sure we handle adding a StreamingHandler to connect to the stderr stream of the Notebook).

**Comment by yannickperrenet** [comment]
Determining whether `orchest.output` has been called before might introduce unexpected behavior when falling back to outputting to disk. Since disk state is not ephemeral we would need to check the metadata for the timestamp on which the data was written, but this does not have to provide any guarantee whether the data was not outputted during the same session. 

So then the question becomes whether we want to treat memory and disk passing differently for this case (which might be strange as they are both invoked through the `orchest.output`). Another possibility would be to clean the disk state when shutting down a session (similarly to what happens with the `memory-server`) so that for both the memory and disk passing it can be checked whether data already exists. But this is a big step back in my opinion.

**Comment by ricklamers** [comment]
I agree, let’s not do this for now. Doesn’t seem necessary.
