### ISSUE TITLE
Improve loading state for toggling sessions

### ISSUE THREAD

**Issue by joe-bell** [orchest/orchest#222]
In it's current state, the session toggle button switches to `disabled` during `STOPPING` or `LAUNCHING` statuses

Although the message changes, it's not immediately clear what's going on. It would be great to add a loading spinner icon

**Comment by yannickperrenet** [comment]
I like the idea!

At the time of implementing the toggle button we were thinking about a spinner as well, making it similar to disabling and enabling Bluetooth on your iPhone. In the end we decided not to go with it, because a session toggle takes some time and might become confusing because the current state is not visible during the toggle. But definitely open to revisiting that decision, especially now that you bring it up.

@ricklamers

**Comment by ricklamers** [comment]
I think we can improve the button further. I’ll leave it to @joe-bell to come up with a proposal to discuss further.

**Comment by yannickperrenet** [comment]
Loading state has been improved some time ago :+1:
