### ISSUE TITLE
Steps point to an old unexisting environment 

### ISSUE THREAD

**Issue by fruttasecca** [orchest/orchest#310]
**Describe the bug**  
Steps point to an old unexisting environment when said environment was deleted, but at the GUI level the environment is set to an existing one.

**To Reproduce**  
- have a project with at least one environment
- have a pipeline with a step pointing to said environment
- delete the environment
- create a new environment (or, alternatively, start with 2 environments in your project)
- in the pipeline editor the step is reported to have switched to an environment that exists (i.e. it's not using  the old, deleted environment)
- run the step
- error given by the fact that the step definition is actually pointing to the old environment

**Expected behaviour**  
What the GUI reports and the step definition should be in sync, one way or another, i.e. either the step having no set environment or the definition being updated with the new environment.

**Comment by yannickperrenet** [comment]
I think there is actually a small nuance here:

1. Have a project with one environment
2. Have a pipeline step point to that environment
3. Delete the environment
4. Create a new environment
5. Run the step (without looking at the step properties in the UI first)

Now the step will try to execute using the old environment (because the old environment is still in the pipeline definition):
![image](https://user-images.githubusercontent.com/26223174/125759098-9ec2c711-7d17-4a7b-8b90-b3b73122b427.png)

Instead if you were to replace step 5. with:
5. Open the step properties in the pipeline editor and then run the step
Then the pipeline definition is updated to use the new environment. Probably because of the drop-down selector behavior.

### Potential fix
When deleting the environment we should probably delete all usage of the environment in the pipeline definitions of the project. The pipeline editor can then handle the fact that no environment is defined.

Alternatively, the pipeline editor should not cause automatic switching to newly created environments BUT still switch automatically to newly build environments, i.e. building an existing environment should cause the resulting environment to be used.
