### ISSUE TITLE
job cronstring is not validated when confirming a draft job

### ISSUE THREAD

**Issue by fruttasecca** [orchest/orchest#377]
**To Reproduce**  
Steps to reproduce the behaviour:

1. Create a job
2. In the draft view, set the cron string to a value that is not a valid cron string
3. Press on "Run Job"
4. The backend will reject the request
5. The client will handle the error by informing the user and bringing the user back to the jobs list view
6. Any unsaved job parameter is lost

**Comment by yannickperrenet** [comment]
To give some context, see the following screenshots.

When an invalid cron string is set, the following is shown to the user:
![image](https://user-images.githubusercontent.com/26223174/125750359-b7824b09-1f82-4fbc-9883-30ae805f9110.png)

Yes, the user could still press "run job" but would be get the dialog:
![image](https://user-images.githubusercontent.com/26223174/125750495-a26b92f2-3846-4ca4-ad6b-0c047777bbe1.png)

I guess you are proposing validating the cron string the moment "run job" is pressed so that the user has to correct the cron string before "run job" works. This way not losing the progress on setting up the job.

**Comment by fruttasecca** [comment]
Yes

**Comment by yannickperrenet** [comment]
> Yes

Good! That is exactly what I implemented in the linked PR.
