### ISSUE TITLE
`orchest-ctl` does not report installation failure if the device is running out of space

### ISSUE THREAD

**Issue by fruttasecca** [orchest/orchest#392]
**Describe the bug**  
Installation failure due to running out of disk space is silent.

**To Reproduce**  
Steps to reproduce the behaviour:

- have a disk that is running out of space
- `./orchest install`
- orchest reports that all services and images have been installed
- `./orchest start` reports that some images are missing, i.e. "are you sure Orchest is installed?"

**Expected behaviour**  
`orchest-ctl` should report that the installation process has failed

**Context**
This might be due to `aiodocker`.

**Comment by yannickperrenet** [comment]
Multiple users have run into this issue so far, and the fact that this issue is hard to debug (especially for new users) indicates that we need a solution.

Possible solutions:
* Have the `orchest` shell script or the `orchest-ctl` (if possible since it is a Docker container) check the available disk size and report if it does not suffice to install Orchest.
* Have the installation process error on invalid disk space.

Additionally we could:
* Mention something like "At least 20GB disk size available" in the main README under requirements (in the installation section)

**Comment by yannickperrenet** [comment]
Since we are now nudging the user towards disk size availability on installation failure I no longer consider this a bug, but instead an improvement we can make over the already improved messaging.

**Comment by yannickperrenet** [comment]
Not directly related, but related to available disk size (after successful installation): https://github.com/orchest/orchest/pull/463.

**Comment by yannickperrenet** [comment]
With the improvements we have made so far to address this issue I think we can consider it solved, even though we have taken a different path to solve the issue.
