### ISSUE TITLE
Save "dirty" open files in JupyterLab when navigating away from the JupyterLab page

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#503]
**Describe the solution you'd like**  
Save "dirty" open files in JupyterLab when navigating away from the JupyterLab page

**What does your solution aim to solve?**  
It's not always clear to the user saving is necessary to propagate changes of behavior. In addition, unsaved changes cause a browser navigation prompt "Are you sure you want to leave..." without JupyterLab showing. Finally, it by default autosaves already so it's not a big change in behavior.

Note: saving files in the JupyterLab UI is a bit glitchy with the recent addition of real-time collaboration in JupyterLab. So we probably want to track JupyterLab upstream closely to make sure we get rid of this glitchy-ness as soon as possible. Glitchiness is there as of  JupytrLab 3.1.12.

**Comment by astrojuanlu** [comment]
> Note: saving files in the JupyterLab UI is a bit glitchy with the recent addition of real-time collaboration in JupyterLab. So we probably want to track JupyterLab upstream closely to make sure we get rid of this glitchy-ness as soon as possible. Glitchiness is there as of JupytrLab 3.1.12.

Been affected by this several times today unfortunately 😓 

I think I'm starting to see a pattern to more easily reproduce the issue:

1. Open a notebook in the JupyterLab interface
2. Make changes in a few cells, leave some without executing them and do not save the notebook (in recent JupyterLab versions, this will show an orange marker on the cell count)
3. Spend some time away from the window (searching docs online, multitasking in general) (I have observed that just a few seconds are not enough)
4. Come back, and press Ctrl+S or click "Save notebook"
5. Observe that the notebook doesn't save: no "Saving started" prompt, no visible errors in the JS console, no user feedback.

The steps above don't guarantee 100 % that the issue appears though. Sometimes it helps to do it with several notebooks at the same time: some of them will get stuck, some won't. Once a notebook gets stuck, it never gets back to a normal state, and any changes done since the last successful save will be lost.

Workarounds that don't work:

- "Close tab -> save" doesn't do anything, leaves the notebook unsaved, and most interestingly, doesn't close the tab (something might be blocking it?)
- Download or duplicate notebook does not avoid the problem, since these use the version saved on disk

Workarounds that do work (for me): 

- Open new notebook, copy cells from unsaved one to new one, save backup notebook quickly, close tab of unsaved notebook discarding changes, open unsaved notebook again, copy cells from backup notebook to unsaved one

**Comment by astrojuanlu** [comment]
And another thing that I observed:

If you make changes to a notebook, a marker appears in place of the ❌ close button of the corresponding tab (good). However, after using other windows for a while and then coming back, it disappears 😳 I'm wondering if it could be related.

JupyterLab 3.3.0b0 was released last week, and a final release is scheduled at the end of this month. I wonder if it would be useful to give this version a spin before getting too deep into the debugging. https://github.com/jupyterlab/jupyterlab/issues/11643#issuecomment-1034526258

**Comment by yannickperrenet** [comment]
> However, after using other windows for a while and then coming back, it disappears flushed I'm wondering if it could be related.

This is probably due to auto-saving that JupyterLab does. The default interval is 120s (as far as I know). 

> Note: saving files in the JupyterLab UI is a bit glitchy with the recent addition of real-time collaboration in JupyterLab.

Is this something you have personally experienced? Or do you know of any upstream issues in the JupyterLab repo? @ricklamers

> I think I'm starting to see a pattern to more easily reproduce the issue

I've tried this and other steps (and disabled auto-saving) but wasn't able to reproduce this issue once. I am on version `3.2.4` which is the latest JupyterLab version that we have shipped inside Orchest. What version did you experience this issue @astrojuanlu?

### Some ideas

* Not start JupyterLab with the `--collaborative` flag (if this is what causes the issue -- I can look into this @ricklamers)
* I tried to use a low auto-save internal (I set it to 5s), but whilst editing and doing an interactive pipeline run at the same time gave the  following prompt. For users this might be very confusing since they didn't press a button and don't know what caused the error.
![image](https://user-images.githubusercontent.com/26223174/154508321-4060cc1a-45e7-4f6d-9f80-dc7e8e74cbff.png)
* Writing our own extension to save "dirty" open files when they lose focus ([existing extension](https://github.com/s-weigand/jupyterlab_autosave_on_focus_change)), but we would get into the same territory due to "File Changed" conflicts as mentioned in the previous point.

[Upstream JupyterLab issue about auto-saving on loss of focus](https://github.com/jupyterlab/jupyterlab/issues/4344).

**Comment by astrojuanlu** [comment]
All this time in a cloud instance, haven't tried locally yet.

**Comment by astrojuanlu** [comment]
I still experience this from time to time on cloud instances, but so far I haven't been lucky trying to reproduce it on purpose. It seems to be time-dependent too, which makes it more annoying. Now I'm trying to reproduce it locally.

>> If you make changes to a notebook, a marker appears in place of the x close button of the corresponding tab (good). However, after using other windows for a while and then coming back, it disappears flushed I'm wondering if it could be related.
> This is probably due to auto-saving that JupyterLab does. The default interval is 120s (as far as I know).

OK, I confirm this and I can see "Saving file" on the jupyter-server logs.

**Comment by yannickperrenet** [comment]
Logs from @astrojuanlu when the issue appeared (at ~16:00) on a cloud instance running Orchest:
```
[I 2022-02-17 15:56:06.080 ServerApp] Saving file at /Experimental dashboard exploration.ipynb
[W 2022-02-17 15:56:40.295 ServerApp] delete /streamlit.py
[W 2022-02-17 15:56:40.296 ServerApp] Skipping trash for /project-dir/streamlit.py, on different device to home directory
[I 2022-02-17 15:56:45.840 ServerApp] Connecting to ws://jupyter-eg-b6c14605-c28d-4145-da3ae621-3523-4805:8888/jupyter-server-b6c14605-c28d-4145-da3ae621-3523-4805/api/kernels/902cb29c-48ed-4735-a9b6-510cb6425135/channels
[I 2022-02-17 15:57:51.012 ServerApp] Saving file at /Experimental dashboard exploration.ipynb
[I 2022-02-17 15:58:42.158 ServerApp] Saving file at /experimental-dashboard.py
[I 2022-02-17 16:00:34.860 ServerApp] Copying Experimental dashboard exploration.ipynb to
[I 2022-02-17 16:00:38.943 ServerApp] Request start kernel: kernel_id=None, path=''
[I 2022-02-17 16:00:40.675 ServerApp] GatewayKernelManager started kernel: 7b73e708-7fee-47ae-9f5e-799147510030, args: {'kernel_name': 'orchest-kernel-08830f51-5544-4e42-9fc8-81b8e03beabd', 'cwd': '/project-dir'}
[I 2022-02-17 16:00:41.177 ServerApp] Connecting to ws://jupyter-eg-b6c14605-c28d-4145-da3ae621-3523-4805:8888/jupyter-server-b6c14605-c28d-4145-da3ae621-3523-4805/api/kernels/7b73e708-7fee-47ae-9f5e-799147510030/channels
[I 2022-02-17 16:00:50.187 ServerApp] Request start kernel: kernel_id=None, path=''
[I 2022-02-17 16:00:51.947 ServerApp] GatewayKernelManager started kernel: 6174902c-ddf4-4bea-881b-7569f8f989ce, args: {'kernel_name': 'orchest-kernel-08830f51-5544-4e42-9fc8-81b8e03beabd', 'cwd': '/project-dir'}
[I 2022-02-17 16:00:52.447 ServerApp] Connecting to ws://jupyter-eg-b6c14605-c28d-4145-da3ae621-3523-4805:8888/jupyter-server-b6c14605-c28d-4145-da3ae621-3523-4805/api/kernels/6174902c-ddf4-4bea-881b-7569f8f989ce/channels
[W 2022-02-17 16:00:55.130 ServerApp] delete /Experimental dashboard exploration-Copy1.ipynb
[W 2022-02-17 16:00:55.130 ServerApp] Skipping trash for /project-dir/Experimental dashboard exploration-Copy1.ipynb, on different device to home directory
[I 2022-02-17 16:00:56.952 ServerApp] Saving file at /Experimental dashboard exploration.ipynb
```
Do you remember what you did when the issue hit again? Did you "Copying Experimental dashboard exploration.ipynb to /Experimental dashboard exploration-Copy1.ipynb"?

**Comment by astrojuanlu** [comment]
> Did you "Copying Experimental dashboard exploration.ipynb to /Experimental dashboard exploration-Copy1.ipynb"?

Exactly, I did that after I noticed the issue to save my unsaved cells.

**Comment by yannickperrenet** [comment]
Alright, I have looked at the source code of [jupyter_server](https://github.com/jupyter-server/jupyter_server) and it would be insanely helpful if you could do the follow when running into the issue again:

1. Delete the checkpoint of the Notebook you are failing to save (delete the file from `.ipynb_checkpoints/`) 
2. Invoke the save again
3. Is the checkpoint file you deleted, created again?

And another check:

1. Watch the file manager in JupterLab (make sure you have enabled showing hidden files -- view > show hidden files)
2. Look for a temporary file being created with the format `.~filename` where `filename` is the name of the Notebook you are trying to save
3. Invoke save
4. Did you see the temporary file being created?

To help with step 4. (since it happens so fast) you can use the following script in another notebook (make sure to have it running before saving the notebook you are looking to save) -- **Note** use the appropriate filename instead of `"explore-data"`:
```python
import os

while True:
    if os.path.exists(".~explore-data.ipynb"):
        print("Found file!")
        break
```
if the execution did not stop and print then the file was not created.

Since we are seeing the following line in the log output:
```
[I 2022-02-17 15:57:51.012 ServerApp] Saving file at /Experimental dashboard exploration.ipynb
```
we know that at least the [`save`](https://github.com/jupyter-server/jupyter_server/blob/745f5ba3f00280c1e1900326a7e08463d48a3912/jupyter_server/services/contents/handlers.py#L172) function of `jupyter_server` is invoked. So the next step would be to find out why it is not actually saving.

**Comment by yannickperrenet** [comment]
Curious to see whether the atomic writes are causing the issue ([source code link](https://github.com/jupyter-server/jupyter_server/blob/745f5ba3f00280c1e1900326a7e08463d48a3912/jupyter_server/services/contents/fileio.py#L189)):

> By default notebooks are saved on disk on a temporary file and then if succefully written, it replaces the old ones.
      This procedure, namely 'atomic_writing', causes some bugs on file system whitout operation order enforcement (like some networked fs).
      If set to False, the new notebook is written directly on the old one which could fail (eg: full filesystem or quota )

**Comment by yannickperrenet** [comment]
Lastly, after the bug hits again you could try whether updating JupyterLab to the latest version solves things (it won't have a direct impact but could prevent the bug from happening again in the future).

In the JupyterLab set-up script ([docs](https://docs.orchest.io/en/latest/fundamentals/configuration.html#configuring-jupyterlab)), simply enter:
```bash
pip install -U jupyterlab
jupyter lab --version
```

**Comment by astrojuanlu** [comment]
Deep into the debugging. Quite difficult because the source is minified, but I'm now comparing it with a local build and things are starting to make sense.

Call stack of the "save" action:

https://github.com/jupyterlab/jupyterlab/blob/3.2.x/packages/docmanager-extension/src/index.ts#L679-L680

https://github.com/jupyterlab/jupyterlab/blob/3.2.x/packages/docregistry/src/context.ts#L307

https://github.com/jupyterlab/jupyterlab/blob/3.2.x/packages/docregistry/src/context.ts#L616

https://github.com/jupyterlab/jupyterlab/blob/3.2.x/packages/docregistry/src/context.ts#L728

https://github.com/jupyterlab/jupyterlab/blob/3.2.x/packages/services/src/contents/index.ts#L829

https://github.com/jupyterlab/jupyterlab/blob/3.2.x/packages/services/src/contents/index.ts#L1239

This in turn sends a `PUT` request to the server. My guess is that this would initiate the "save" code of jupyter_server.

**Comment by astrojuanlu** [comment]
I set a breakpoint at https://github.com/jupyterlab/jupyterlab/blob/3.2.x/packages/docregistry/src/context.ts#L307 and:

1. For non-blocked notebooks, `Ctrl+S` was going through that breakpoint, and saving the notebook as normal.
2. For blocked notebooks, the breakpoint was not getting visited.

I cannot go up in the stack from there because the rest are promises that get registered at various points.

On the other hand, all those functions look similar from 3.2.x to 3.3.x, so I'm not very confident that upgrading will do anything.

---

Interestingly, Chromium Dev Tools are able to fully unminify the code including comments, whereas Firefox only does it partially. Yes, this is me figuring out how frontend development works in 2022 😂 Will give this another try tomorrow.

**Comment by yannickperrenet** [comment]
Really useful debugging info! :muscle: 

> https://github.com/jupyterlab/jupyterlab/blob/3.2.x/packages/docregistry/src/context.ts#L307

How about setting a breakpoint at the promise that calls `this._provider.acquireLock()` ([L302](https://github.com/jupyterlab/jupyterlab/blob/3.2.x/packages/docregistry/src/context.ts#L302)). Sounds like it tries to acquire a lock but can't, hence the blocking behavior.

> My guess is that this would initiate the "save" code of jupyter_server.

That is correct ;)

**Comment by astrojuanlu** [comment]
> How about setting a breakpoint at the promise that calls `this._provider.acquireLock()` ([L302](https://github.com/jupyterlab/jupyterlab/blob/3.2.x/packages/docregistry/src/context.ts#L302)). Sounds like it tries to acquire a lock but can't, hence the blocking behavior.

The "Saving started" status doesn't appear until the lock has been acquired. So, perhaps you're right and the function gets stuck there, waiting for a lock that never arrives?

> Lastly, after the bug hits again you could try whether updating JupyterLab to the latest version solves things

I didn't know that I could easily upgrade the JupyterLab version. Do you think I could install a custom one too? That way we could instrument the JS a bit more (i.e. filling it with `console.debug`).

---

After writing the above, I went again to the JupyterLab issue tracker to find related issues, and this time I was successful:

https://github.com/jupyterlab/jupyterlab/issues/11348

The user reports this issue after spam-clicking the "save" button: I went back to our instance, did that, and 🪄 the issue was there.

It seems to be directly related to some issues with the `--collaborative` flag:

https://github.com/jupyterlab/jupyterlab/issues/10852

and looks like we are not alone:

https://discourse.jupyter.org/t/plans-on-bringing-rtc-to-jupyterhub/9813/13?u=astrojuanlu

Given all this soft evidence towards glitches on the `--collaborative` mode of JupyterLab, I think we should disable it from here until it's declared more stable:

https://github.com/orchest/orchest/blob/c37eb86e510a6c319261c1f158a60e89bea7b86c/services/jupyter-server/start.sh#L56

**Comment by astrojuanlu** [comment]
>> How about setting a breakpoint at the promise that calls this._provider.acquireLock() ([L302](https://github.com/jupyterlab/jupyterlab/blob/3.2.x/packages/docregistry/src/context.ts#L302)). Sounds like it tries to acquire a lock but can't, hence the blocking behavior.

> The "Saving started" status doesn't appear until the lock has been acquired. So, perhaps you're right and the function gets stuck there, waiting for a lock that never arrives?

After being able to reliably reproduce this issue and debugging it in Chromium, I confirm this is what happens ✔️
