### ISSUE TITLE
Support multiple client sessions per user

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#570]
**Describe the solution you'd like**  
Support multiple user sessions per user

**What does your solution aim to solve?**  
Right now a user is logged out of their browser client when the same user is logged in someplace else. We ideally want to support multiple client sessions per user.

**Comment by yannickperrenet** [comment]
After I quick look, it is probably caused by how we do authentication based on the token in the cookie:

https://github.com/orchest/orchest/blob/e082a136524bea29968a47729ea38e7ca3a3e541/services/auth-server/app/app/views.py#L60-L64

and

https://github.com/orchest/orchest/blob/e082a136524bea29968a47729ea38e7ca3a3e541/services/auth-server/app/app/views.py#L170-L176

We instead need the ability to have multiple tokens for one user.
