### ISSUE TITLE
Stuck on payment screen after adding card/charge to card

### ISSUE THREAD

**Issue by nickdickinson** [orchest/orchest#580]
**Describe the bug**  
Stuck on cancel payment screen after adding credit card. Incorrect information about no charge (in fact there was a 1 USD charge to the card).

**To Reproduce**  

1. Go to 'Add first instance'
2. Click on 'Add a credit card (I also added VAT info)'
3. Wait and confirm payment (this was a mastercard)
4. See error: stuck on screenshot below... only option is to either refresh or cancel payment. User does not know what to do.

**Expected behavior**  
Go to new free instance / new project or some update on waiting for payment or other instructions to proceed. Charge already made to card.

**Screenshots**  
![image](https://user-images.githubusercontent.com/1900032/144997689-3f079850-8d70-460d-a26f-3418c02116ef.png)

**Environment**

- OS: Windows 10
- Browser: Chrome
- Version: 96.0.4664.45 (Official Build) (64-bit)
- Environment: Production / live website
- Logs: Not relevant, this is a user report

**Additional context**  
NA

**Comment by ricklamers** [comment]
Thanks for reporting this, we’ll look into it 👍🏻

Obviously, neither should happen.

**Comment by nickdickinson** [comment]
Additional detail: second time around it worked. The difference: I added the VAT number only after first clicking on credit card. Also the 1 USD charge was not claimed in the end and was returned from the first time around.

**Comment by iannbing** [comment]
@nickdickinson Thanks for reporting. Glad to hear that it worked with your second attempt. 
After looking at logs from our side and several attempts to reproduce this issue, it's most probably because the form was not submitted successfully and our app hangs because it didn't expect this error. We added an error-handling, so the app will tell user about the error and ask user to try again.

Feel free to re-open the issue if it still persists.
