### ISSUE TITLE
Plotly interactive plots should work out of the with the default JupyterLab configuration

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#637]
**Describe the bug**
Plotly interactive plots should work out of the with the default JupyterLab configuration, that isn't always the case. This could be due to a misconfiguration of IPyWidgets in JupyterLab

**Expected behavior**
Plotly interactive widgets should work in Orchest out of the box.

Addition work:
- Add docs instruction on troubleshooting steps if rich cell output like a Plotly chart don't work.

**To Reproduce**

1. Create a notebook (and make sure you have an environment with Plotly)
2. Run a cell that plots Plotly
3. Observe whether it's a rich HTML element or static plot or error

**Comment by yannickperrenet** [comment]
The plotly plot simply doesn't show and you are faced with a blank canvas. This can easily be fixed though by adding:
```bash
pip3 install jupyter-dash
```
to the jupyterlab configuration file and build it. I don't think it makes sense to bloat the `jupyter-server` image even more by adding it there.

On the other hand, instead of opening the file in JupyterLab and using the *view file* functionality it renders just fine.

Shall I just add the instructions to the docs?

**Comment by yannickperrenet** [comment]
According to the [plotly docs](https://plotly.com/python/getting-started/#jupyterlab-support):

> You'll need jupyter-dash to add widgets such as sliders, dropdowns, and buttons to Plotly charts in JupyterLab.

The issue is the one described in: https://github.com/plotly/plotly.py/issues/2672. And so possible other fixes (apart from the `jupyter-dash` install) include:
```python
# Explicitly using another renderer that does work
fig.show(renderer="iframe")

# Or setting the default renderer so you don't have to pass it every time
import plotly.io as pio
pio.renderers.default="iframe"
```

Seems like it is the default renderer that is used does not work in JupyterLab by default.

And so the best solution seems to be to add it some instructions to our docs :thinking:

**Comment by yannickperrenet** [comment]
Actually I found:
> It is also possible to set the default renderer using a system environment variable. At startup, plotly.py checks for the existence of an environment variable named PLOTLY_RENDERER. If this environment variable is set to the name of an available renderer, this renderer is set as the default.

So that could be a great alternative.
