### ISSUE TITLE
JupyterLab build causing CPU utilization spikes

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#655]
**Describe the bug**
On session start the JupyterLab service triggers a build which causes Orchest to become unresponsive.

**Expected behavior**
Builds should only be triggered explicitly if a users confirms the build dialog.

**To Reproduce**
Not sure exactly how to reproduce.

**Environment**
- OS (e.g. macOS): Linux
- Browser (e.g. Chrome): Brave
- Orchest's version (in the settings page): v2022.01.2

**Comment by yannickperrenet** [comment]
I've gone over the [`start.sh`](https://github.com/orchest/orchest/blob/master/services/jupyter-server/start.sh) script and didn't see anything that made me believe that we trigger a build before starting JupyterLab (as I expected).

We updated to JupyterLab `3.2.4` on `2021-12-15` so that is likely unrelated. Will try to reproduce by adding extensions as that seems to be the only way to trigger this (although I recently coincidentally did so and I remember getting a confirm modal in JupyterLab asking me to build, but maybe it was building regardless of my answer).

**Comment by yannickperrenet** [comment]
Wasn't able to reproduce. Below follows a write-up of what I did.

JupyterLab configuration bash script:
```bash
jupyter labextension install @deathbeds/ipydrawio --no-build
```
install a source extension that requires a rebuild and explicitly do not build to make sure a build is not triggered.

Next I opened JupyterLab and got the prompt asking to build (as expected):
![image](https://user-images.githubusercontent.com/26223174/153637522-46f0e18c-a79f-4fe8-8202-415e4d367333.png)

Once I pressed _Build_ it started to build. From the moment that JupyterLab started I monitored the processes on my system and only found the build processes to start once I clicked the _Build_ button.

So from what I can tell the expected behavior listed in the issue seems to be the current behavior.

**Comment by yannickperrenet** [comment]
> which causes Orchest to become unresponsive.

Here I found a potentially related issue on the JupyterLab repo: https://github.com/jupyterlab/jupyterlab/issues/4824

In short, builds might fail due to the memory usage when installing "many" extensions. This could mean that you saw the build not failing but using enough memory to make Orchest feel unresponsive. 

(Feel free to re-open the issue if I missed something or the issue persists.)
