### ISSUE TITLE
Service configuration collapses when browser tab regains focus

### ISSUE THREAD

**Issue by astrojuanlu** [orchest/orchest#729]
**Describe the bug**
I have the Pipeline settings -> Services of a Pipeline in one browser tab, and there is one service configured. If I expand the service configuration, leave the tab, and come again, the service configuration collapses and I have to expand it again.

**Expected behavior**
I expected the service configuration to not collapse unless I decide to do it myself.

**To Reproduce**

1. Go to Pipeline settings -> Services
2. Create a service, and save it
3. Keep the service configuration open, and change tab or window
4. Come back to tab, click on any blank area of the page, and see the service configuration collapse.

**Screenshots**
Here I demonstrate the issue with 2 tabs:

https://user-images.githubusercontent.com/316517/154517640-d8517fa3-03bd-41da-86df-e7696201b889.mp4

**Environment**

- OS: Linux Mint
- Browser: Firefox
- Orchest's version (in the settings page): `v2022.02.8`

**Comment by iannbing** [comment]
I think we need more clarifications for this specific case.

Since Orchest allows multiple users managing the same instance at the same time, one of the principle for Orchest FE is to re-validate the UI when tab re-gain focus, in order to ensure (as much as possible) that user is working with the latest server-side state.

And because of this, the form will be refreshed and the service form in the table is reset to default. To solve this issue, we could persist the UI state of the form in the localstorage or a URL query args. @ricklamers I think query args would be a slightly better option. What do you think?

**Comment by iannbing** [comment]
Or we could also introduce auto-save just like environment edit page.

**Comment by yannickperrenet** [comment]
> introduce auto-save, so user doesn't lose input data when switching tabs

I really like this approach (relates to #426). No one expects to lose data by switching tabs, at least I don't :smile: 

> use query args to persist the form state to keep the form open when re-gain focus.

When it comes to this, I don't think it has that much priority but would be a nice quality of life improvement.
