### ISSUE TITLE
Instance volume space alert?

### ISSUE THREAD

**Issue by astrojuanlu** [orchest/orchest#741]
Today I received an email saying:

> Your instance {name} is running out of available disk space. You still have 10 GB left out of the total 50 GB.

However, I didn't do anything special to consume that much disk space. I did upgrade it to the latest version recently.

I opened a terminal from JupyterLab to try to find out what is going on, and I get this:

```
# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          46G   38G  7.7G  84% /
tmpfs            64M     0   64M   0% /dev
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
shm              64M     0   64M   0% /dev/shm
/dev/root        46G   38G  7.7G  84% /data
tmpfs           3.9G     0  3.9G   0% /proc/acpi
tmpfs           3.9G     0  3.9G   0% /proc/scsi
tmpfs           3.9G     0  3.9G   0% /sys/firmware
# du -sh /* 2> /dev/null | sort -rh | head
1.5G    /usr
421M    /jupyter-extensions
55M     /root
36M     /jupyterlab-orchest-build
27M     /var
9.3M    /lib
5.2M    /bin
3.9M    /sbin
2.4M    /project-dir
1.5M    /etc
```

So, I have no idea where those 38G are coming from.

Is there a way to properly diagnose this? Or do a cleanup of temporary data or similar?

**Comment by yannickperrenet** [comment]
> I did upgrade it to the latest version recently.

This is a known issue with old instances. The issue is caused by dangling GPU environments (`orchest-base-kernel-py-gpu`) that fail to be cleaned up on update. We have shipped a fix for future versions but are unable to delete these dangling GPU environments programmatically on older instances. If anyone runs into this issue, we would be happy to manually fix it for them.

> Is there a way to properly diagnose this? Or do a cleanup of temporary data or similar?

Sadly, there is not. It would be a task for the "sysadmin" that controls the underlying infrastructure (with Orchest not yet running on Kubernetes this means a single VM). When using the Orchest Cloud we are working hard to provide the best experience possible and taking care of these tasks for you. 

Do you think it makes sense to broaden the scope of #683 past the `userdir`?

**Comment by astrojuanlu** [comment]
Thanks @yannickperrenet , that makes sense!

> Do you think it makes sense to broaden the scope of https://github.com/orchest/orchest/issues/683 past the userdir?

If I'm being billed for it, yes :) If that space does not count against my quota, then I wouldn't care. But then if this is something that can't be really controlled by the user, perhaps it should be left out of the quota?
