### ISSUE TITLE
Docker error while installing Orchest: too many levels of symbolic links

### ISSUE THREAD

**Issue by megha120** [orchest/orchest#848]
I am getting the below error while installing orchest using 'bash orchest install':

docker: Error response from daemon: error creating overlay mount to /var/lib/docker/overlay2/a3534df899b9d4314c714596bab8b515cedc0af829f59785d5e701b4dada794e-init/merged: too many levels of symbolic links

I am following the steps mentioned here: https://docs.orchest.io/en/stable/getting_started/installation.html using WSL2 on windows 10.

![image](https://user-images.githubusercontent.com/65885522/160992358-b534314e-200c-4a6a-b7ec-eb05b3a6b7bd.png)

**Comment by yannickperrenet** [comment]
Hi @megha120. Sorry to hear that the installation is not working for you.

I've not seen that error before, nor am I running on WSL2 myself so I will just make an educated guess on what causes the issue. Looking at Docker related issues (e.g. https://github.com/docker/for-win/issues/5763) it seems that the issue could be related due to available disk size.

In order to free up disk space, you could run `docker system prune` and then try the install again.

Hope that works! Let me know if it doesn't :innocent:

**Comment by yannickperrenet** [comment]
Did freeing up disk space solve the issue for you? Would love to better understand where thinks are breaking for you to improve our installation documentation (and of course so that you can enjoy using Orchest).

**Comment by yannickperrenet** [comment]
I am considering the issue to be stale, please feel free to reopen.
