### ISSUE TITLE
Allow downloading of the root project folder

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#853]
**Describe the problem this improvement solves**
Sometimes you want to share a project with someone by downloading all project files and sending them the zip instead of going through VCS systems like `git`.

**Describe the solution you'd like**
Allow download root project folder as zip like we allow any subdirectory to currently be downloaded.

Up for debate: allow users to download the other root folder (`/data`) too. It's usually probably pretty big.

**Comment by yannickperrenet** [comment]
Isn't it good enough that you can easily select all files in the project root and then download them?

**Comment by ricklamers** [comment]
> Isn't it good enough that you can easily select all files in the project root and then download them?

I would argue that's not good enough as it feels quite error prone. Feels like this is a small change that would make it simpler

**Comment by yannickperrenet** [comment]
@ricklamers Do you think it makes sense to update the issue description to include downloading a selection of files as a `zip` archive instead of downloading all the selected step individually?

![image](https://user-images.githubusercontent.com/26223174/184159425-0676d744-dfd4-4598-8b1f-2298d534f2af.png)

Doing this (and pressing download) would actually lead to three separate download requests instead of just one (and putting all files in a zip).
