### ISSUE TITLE
Install on GKE cluster

### ISSUE THREAD

**Issue by mtojek** [orchest/orchest#930]
Hi folks,

I tried to play with the product and evaluate its developer experience, but unfortunately, I got stuck on the installation level. I tried to install it on the GKE cluster, first using AutoPilot, then Standard one. In both cases, helm found the following problems:

1. Volume size of 999Ti is not a valid value as it exceeds int64.
2. GKE's PersistentVolumeClaims don't operate in `ReadWriteMany` mode.

Is it a known issue with GKE and it isn't supported or should I adjust the cluster configuration somehow?

Kind regards,
Marcin

EDIT:

I quickly skimmed through the [operator PR](https://github.com/orchest/orchest/pull/916), but it looks like it's also affected by this issue.

**Comment by astrojuanlu** [comment]
Hi @mtojek, thanks a lot for your interest in Orchest! As you already saw, we are working hard on it and polishing the edges. There's some more context in #885 but the work is in #916 - we hope we can iron out the last rough edges in the coming days.

**Comment by mtojek** [comment]
Hey @astrojuanlu, do you think that you will be able to solve these blockers for GCP deployment?

**Comment by astrojuanlu** [comment]
Hi @mtojek! I pinged the team to get a more qualified answer on that. In the meanwhile, notice that we merged the Orchest Operator already.

**Comment by nhaghighat** [comment]
Hi @mtojek , Thanks for reaching out. we just released our Kubernetes Operator. We recommend installing orchest via `orchest-cli`, but unfortunately, it is not possible to change volume size with `orchest-cli` at the moment. but you can change the volume size by deploying `[orchest-controller](https://docs.orchest.io/en/latest/getting_started/installation.html#deploy-orchest-controller)` into your cluster and deploy orchest by creating a OrchestCluster CRD.

A sample orchest-crd can be found here: https://github.com/orchest/orchest/blob/orchest-crd-example-and-doc/services/orchest-controller/deploy/example/orchest.yaml

note: since the project is under heavy development, this approach is **not recommended** for stable deployment.

**Comment by mtojek** [comment]
@nhaghighat I appreciate the heads up, but you didn't answer the original question: does this stack work in public cloud providers with managed k8s like GCP, AWS, and Azure? Have you verified and do you support orchest there?

**Comment by mtojek** [comment]
Alright, that justifies all GCP issues I faced. I will keep an eye on the project :)

**Comment by yannickperrenet** [comment]
Relates to the more general issue of installing Orchest on a non-minikube cluster: #885. Happy to keep this open to track progress on GKE specifically :100:

**Comment by yannickperrenet** [comment]
With the merge of #1048 we now support running Orchest on GKE (will be as of release `v2022.07.2`) and installation instructions can be found in [the docs](https://docs.orchest.io/en/latest/getting_started/installation.html#install-orchest).
