### ISSUE TITLE
On load of project without pipeline prompt to create a pipeline automatically

### ISSUE THREAD

**Issue by ricklamers** [orchest/orchest#948]
**Describe the problem this improvement solves**
It's not immediately clear how to proceed when creating an empty project as a first time new user when you see this:

**Screenshots**
![image](https://user-images.githubusercontent.com/1309307/168325093-f4b78cbc-f75a-4586-bdba-bd6ac0fc8beb.png)

**Describe the solution you'd like**
"Pre-click" the create pipeline button on pipeline editor load if the project contains no pipelines.

**Comment by astrojuanlu** [comment]
Or display the "create pipeline" more prominently the first time?

**Comment by yannickperrenet** [comment]
I am also in favor of prominently adding an action to "create pipeline", for example in the middle of the pipeline canvas. Creating a pipeline right of the bat feels somewhat intrusive. New users might just want to check out the view instead of being forced into an action. Moreover, let's say they "cancel" out of the option then I think it is good practice to still prominently point them towards the right action, i.e. creating a pipeline.
