### ISSUE TITLE
Switch between pipelines using sessions list

### ISSUE THREAD

**Issue by fruttasecca** [orchest/orchest#959]
**Describe the problem this improvement solves**
Currently, both the toggle button (`1` in the picture) and the pipeline name (`2`) toggle the pipeline
session when clicked.

**Describe the solution you'd like**
 My suggestion would be to have `2` switch between pipelines, and leaving 1 unchanged.

**Screenshots**
![image](https://user-images.githubusercontent.com/19429509/168811292-ed260289-9bc6-4933-86ac-f21f9c590ca6.png)

**Comment by yannickperrenet** [comment]
@ncspost @ricklamers What do you think?

Personally, I feel that the proposed behavior is somewhat confusing given that it is part of the `Sessions` "block". Generally not only the toggle but also the name tend to toggle and I would rather stick with such conventions (if it really is one). 

If we want to make switching between pipelines easier, instead of having to find them within all the files in your project then I think that is a valid point but I don't think this is the way to do it.

**Comment by ricklamers** [comment]
We'll name block "Pipelines" and add a "Session column" to make the block's purpose clear and still get the benefit of the utility of Orchest "finding" all the pipelines in the project for you, and allowing for easy switching.
